// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnlofwunhgitzjozvigz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubG9md3VuaGdpdHpqb3p2aWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTAzMjQsImV4cCI6MjA3MjA4NjMyNH0.v56az885rWG8D4BCrLHk4jUPC4OAY8qiAashQy4muG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});